### ISSUE TITLE
last 60 minutes -last 24 h last day

### ISSUE THREAD

**Issue by sokatra** [bp2008/pingtracer#10]
hy, it would be nice if you can add the feature to display only the last 60 minutes - or the day, because if i see a outage in the log from yesterday it takes ages to sidescroll to the time where it happens.

Perhaps you can implement a "zoom" feature

kind regards

**Comment by bp2008** [comment]
In Tools > Options, increase the graph scrolling multiplier. Try a value of 20.  This will enable you to scroll further with less mouse movement.

Zooming would require a much more complex graph control, and I simply don't have time for it.
