### ISSUE TITLE
route change detection

### ISSUE THREAD

**Issue by sokatra** [bp2008/pingtracer#11]
can you implement the feature to detect route changes during monitoring?
I tried your program an i have done the following
1. i pinged a webserver -everything is fine
2. i connected to a vpn - now pingtracer doesn't recognize the new route

It would be nice if pingtracer can to that

**Comment by bp2008** [comment]
I agree it would be nice, however I do not have a clean way to do this without totally mangling the user interface.  Maybe https://www.pingplotter.com/ can do something like that though.
