### ISSUE TITLE
Feature Request: Adjust Latency Resolution?

### ISSUE THREAD

**Issue by xekon** [bp2008/pingtracer#15]
I am using ping tracer to monitor the ping between myself and my ISP to help diagnose issues.

generally for the single hop from my home to my isp latency is less than 20ms. I am wondering if there is a way to resize the graph to shower greater vertical resolution basically I only need to see a graph that shows between 0ms and 60ms.

good 0-30
bad 30-40
worse 40-60

![image](https://user-images.githubusercontent.com/106644/69000329-8b0ee000-0882-11ea-9721-7e10e5f9a994.png)

**Comment by bp2008** [comment]
Not with the current code.  That would need to be added, and I simply do not have time for it.

I suggest you try [PingPlotter](http://www.pingplotter.com/products/free.html?pk_campaign=header) as its graphic options may be more suited for your goal.
