### ISSUE TITLE
Settings/state reset

### ISSUE THREAD

**Issue by JVimes** [bp2008/pingtracer#18]
I tweaked settings in both the main UI and in Options. I wanted to reset them all, but there doesn't appear to be a way.

I tried deleting `%USERPROFILE%\AppData\Roaming\PingTracer`, but then Ping Tracer gives:  
> System.IndexOutOfRangeException: Index was outside the bounds of the array.
>   at PingTracer.MainForm.controllerLoop(Object arg)

Suggest adding a way to reset the program state to default. It would be nice if Ping Tracer just created a delete-able settings file next to the .exe, since it's otherwise a portable app already. Thanks.

**Comment by bp2008** [comment]
Deleting that folder (or the settings file inside it) should be all you need to do to reset everything to defaults.  I can't imagine why deleting it would cause an issue for you.

**Comment by JVimes** [comment]
Thanks for the follow up. Here's why:

```
System.IndexOutOfRangeException
  HResult=0x80131508
  Message=Index was outside the bounds of the array.
  Source=PingTracer
  StackTrace:
   at PingTracer.MainForm.controllerLoop(Object arg) in C:\...\pingtracer\PingTest\PingTest\MainForm.cs:line 147
```

![image](https://user-images.githubusercontent.com/6148201/88468093-ec6c6180-ce9b-11ea-9c8a-d23daed0ae4e.png)
