### ISSUE TITLE
A Release for Ubuntu Linux LTS versions requested, esp. for Ubuntu-Mate 20.04.latest!

### ISSUE THREAD

**Issue by nonlinear-chaos-order-etc-etal** [bp2008/pingtracer#19]
=)

**Comment by nonlinear-chaos-order-etc-etal** [comment]
A version built for target Ubuntu 16.04.x would also be binary compatible with more recent versions.....

**Comment by bp2008** [comment]
Version 1.8 runs fine on Ubuntu 20.04.  You just need to install mono first.

```
sudo apt install mono-complete
```

Version 1.9 shouldn't work outside of Windows because it uses a different ping library.  I'll try and remember to revert that and release another update soon.

**Comment by bp2008** [comment]
Version 1.10 and forward should work on linux via mono again.

**Comment by bp2008** [comment]
I note that the app is very buggy when running in mono on Linux.  Fundamental things are broken, like _the stop button_ and _tracing routes_ and also _saving a screenshot of the graphs_.  I have no idea how much effort those things would take to fix.  I've never even run a C# IDE on linux, which may be necessary to properly debug there.  With limited time, I would rather focus my efforts on PingTracer 2.0 which will be a full rewrite with a more modular code base.  If a different pinging library has to be used on Linux than on Windows, for example, I want that to be easy to implement. 

I have big plans for PingTracer 2.0.  1.x works fine (on Windows) if you know the IP addresses or hostnames you want to monitor. 
 But my main goal with PingTracer 2.0 is to make it easier to monitor connections you know nothing about.  I want to show a list of running processes with network activity, much like [LiveTcpUdpWatch from NirSoft](https://www.nirsoft.net/utils/live_tcp_udp_watch.html) but with only one row per process.  Selecting one of those processes would begin active monitoring of the remote hosts that process is communicating with. I could render something resembling an RF waterfall view for each one, to show the latency of each route over time.  Then you could click any of those hosts to see full detail for the route to that host (all the IP addresses, precise latency, etc) like the graph stack in PingTracer 1.x.

Of course, PingTracer 2.0 will also support manual IP/host entry, and this will benefit from other improvements I want to make such as faster trace route and asynchronous DNS lookup..
