### ISSUE TITLE
Clearing Successful and Failed counters

### ISSUE THREAD

**Issue by elmorekevin** [bp2008/pingtracer#2]
I'm not sure if this was by design or not, but should stopping and starting clear the counters?

I could see how some might want to keep the stats from the last polling session, but usually when I restart polling I'd prefer the successful and failed counters to clear, as the graphs also clear.

Thanks!

**Comment by bp2008** [comment]
I think it would make more sense to clear those counters when the graphs
are cleared.  Will do.

**Comment by bp2008** [comment]
I finally got around to doing this.  Sorry it took so long :)
