### ISSUE TITLE
Feature request: display % loss on given sliding window

### ISSUE THREAD

**Issue by SagePtr** [bp2008/pingtracer#21]
At this moment, it seems Ping Tracer shows loss percentage on pings visible on the graph. I'd like to be able to configure the time taken into account when showing loss percentage, for example, % loss in last minute, last 10 minutes, last hour, etc. This will be more informative, i think.

**Comment by bp2008** [comment]
Hi.  I appreciate the feedback.  You're right, the loss is only calculated for pings visible on the graph.

I'll be honest, I doubt I will ever implement this in PingTracer.  My time is split too many ways and I would not use this capability myself which makes it a very low priority.

I suggest you try [pingplotter](https://www.pingplotter.com/products/standard.html).  I don't know if it will do what you want any better, but it is a commercial product with several cost tiers (including free) and maybe it will do what you want.

**Comment by SagePtr** [comment]
> I suggest you try pingplotter. I don't know if it will do what you want any better, but it is a commercial product with several cost tiers (including free) and maybe it will do what you want.

I moved off PingPlotter because it became overbloated, i love small & lightweight & portable tools.
