### ISSUE TITLE
Is there a mac os version planed?

### ISSUE THREAD

**Issue by Maxl94** [bp2008/pingtracer#22]
First thanks for your great work. I really enjoy the ping tracer - it works perfect to diagnostic problems in home network. Fritz Mesh makes a lot of troubles :confused:.

But I also need to use the tracer on the Mac of gf. Is a mac version planed? Or could you provide a mac build. Since the traces is build in  C# chances are low, aren't they?

Thanks for your answer!

**Comment by bp2008** [comment]
I don't use macs myself and have no plans to begin.  The existing PingTracer can run in mono which is basically the .NET framework for mac/linux, however PingTracer is very buggy on Ubuntu so I expect it to be very buggy on Mac as well.  The next PingTracer major version should work better but will not be ready any time soon.

**Comment by Maxl94** [comment]
Okay - thanks for your fast reply.
