### ISSUE TITLE
Feature request: Ability to add a related IP to watch

### ISSUE THREAD

**Issue by fencepost** [bp2008/pingtracer#23]
The specific situation that makes me think about this is watching a Comcast-connected endpoint with a static IP. In configurations like that there's both a Comcast cable modem with its own IP address and the assigned static IP address that the end equipment/router gets, but the cable modem IP doesn't show up on a traceroute. By watching both the final IP and the "related" IP of the invisible upstream device you can see whether issues are with the endpoint or with connectivity one hop out from it.

If you're watching from inside a network connected like this you'd typically be watching connections to the router, to the cable modem on 10.1.10.1 (may vary), and to something else external. 

Edit: Another useful option could be watching connectivity across a VPN connection and to the external IP of the same destination.

**Comment by bp2008** [comment]
When I need to monitor a more complex set of targets, e.g. one automatically traced route plus another host, I just run two instances of pingtracer.

**Comment by ScottBeeson** [comment]
You can put multiple IP addresses in the target field separated by commas.  Or is my copy just magical?

**Comment by bp2008** [comment]
@ScottBeeson Yes, that has been possible since version 1.6 in 2017.  But it disables traceroutes when you've entered more than one host this way.
