### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by DerekFroese** [bp2008/pingtracer#3]
Very happy to have found this software, it's quite useful! Like MTR but graphical for Windows. 

If I may humbly suggest some features that I would find useful:

- Ability to manually input IPs to be pinged rather than using output of a traceroute. 
---Sometimes it's handy to choose what you want to monitor - i.e. check latency to the switch that's in between you and a router that won't show up as a hop on a traceroute. 
---Sometimes you may want to check pings to multiple ISPs or targets in different countries
- Ability to choose less than 1 ping/sec. i.e. 1 ping / 5 sec. 
Sometimes I need to monitor network latency over a few days, and having 1 ping/sec means I can't see enough history. 

Thank you so much for developing this!

**Comment by DerekFroese** [comment]
Just occurred to me that adding the ability to scroll or zoom the graph window would also solve the issue :)

**Comment by bp2008** [comment]
Hello!

You can input multiple addresses (comma separated) already.

In tools > options you can increase the number of cached responses.  604800 for example should be 1 week at 1 ping per second.  I'll think about enabling a longer ping interval though.

**Comment by DerekFroese** [comment]
Oh, that's amazing! Thanks for the quick and thorough response.

**Comment by lwarneminde** [comment]
You can actually have less than 1 ping per second - if you type 0.2 in the 'Rate' spinbox it'll change to 0 when you tab away, but it'll still work and do 1 ping every 5 seconds.

**Comment by bp2008** [comment]
Haha nice trick.  I had never tried that.

I've just pushed a version 1.7 release which includes a new dropdown box for choosing between "pings per second" and "seconds per ping", supporting up to 600 seconds or 10 minutes per ping.

**Comment by DerekFroese** [comment]
Amazing! thank you!
