### ISSUE TITLE
Feature Request [Simple]: Add Digits to Interval Field

### ISSUE THREAD

**Issue by cregnier** [bp2008/pingtracer#30]
It seems that you support <1 sec per ping, yet it would be nice to have a way to see this :-)

For example, I would like to set 0.2 seconds per ping.  It seems that this is an valid value yet only shows 0.

Also would be cool as a bonus to set the size of the ping (assuming you are using 32 bytes?).

**Comment by bp2008** [comment]
Hi.

Change the value of the dropdown box to "pings per second" to go faster than 1 second.

![image](https://user-images.githubusercontent.com/5639911/157684171-02ffc9f3-4b52-4ec4-a47d-9f207618c9af.png)

I don't expose a setting for ping size.  It is just the default size which is a 32 byte buffer according to MSDN docs.  That doesn't include protocol headers or any other metadata, so when it is all said and done the ping will be significantly larger (closer to double that size).
