### ISSUE TITLE
Bug: When toggling to "graph only" view, the graph area is larger than the window area

### ISSUE THREAD

**Issue by ScottBeeson** [bp2008/pingtracer#35]
This is especially noticeable in Full Screen as it cuts off the labels.

Here is a screenshot of the window (ALT+PRNTSCR) in normal mode. It is 762x672

![image](https://user-images.githubusercontent.com/108358/157905640-ead71a59-3661-45e5-a5e4-2e7211ca8cb6.png)

And without resizing, here is graph mode. It is 780x681

![image](https://user-images.githubusercontent.com/108358/157905732-d35e545e-2f81-41ce-90b3-b4e2f3338ff1.png)

**Comment by bp2008** [comment]
Alas, I'm aware, and I'm sorry.  I think it is because of the shadows that get drawn around each window, so the OS says the window is larger than it actually is.  I never figured it was enough of an issue to try working around it.
