### ISSUE TITLE
Is there a Portable Mode?

### ISSUE THREAD

**Issue by fubaWoW** [bp2008/pingtracer#36]
Hi there,
is there a "Portable Mode"? -> meaning do not write any file in Appdata folder but instead read config from Program Folder?

**Comment by bp2008** [comment]
Not currently, sorry.  I started writing a lot of my apps to save their configuration in appdata because otherwise there can be write permission errors depending on where people run it from.

**Comment by fubaWoW** [comment]
did it myself and maybe you can adopt it?

just replace
```c#
return Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData).TrimEnd('/', '\\') + "/PingTracer/";
```
with
```c#
string path = Environment.CurrentDirectory.TrimEnd('/', '\\') + '/';
if (!File.Exists(path + "settings.cfg"))
{
	path = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData).TrimEnd('/', '\\') + "/PingTracer/";
}
return path;
```
so if there is a settings file in application directory it will use this first, if not use appdata

**Comment by bp2008** [comment]
Done.  This change will be there if/when I ever do another release.

**Comment by fubaWoW** [comment]
sure, no pressure and thanks for the tool btw! :)
