### ISSUE TITLE
Timeline is not continuous

### ISSUE THREAD

**Issue by sokatra** [bp2008/pingtracer#37]
In pingtracer 1.12.1.0 is unfortunately still the bug in that the time list in the graphical overview is not properly scrollable back. For example, if you run a ping overnight and then scroll the graphic completely to see ping failures graphically, then at certain points the wrong time is displayed.
I.e. the timeline is not continuous and logical.
For example the timeline jumps from 9 am to  6 am
![timeline1](https://user-images.githubusercontent.com/17703360/162904360-5a96916b-4832-4430-9520-818332d744f5.PNG)

Kind regards Sokatra

**Comment by sergeevabc** [comment]
> Anyway I'm not actively maintaining pingtracer 1.x anymore
Why? What do you recommend to use then?

**Comment by bp2008** [comment]
>>Anyway I'm not actively maintaining pingtracer 1.x anymore
>
>Why?

I just don't have much time to spend on this app.  I'm fixing this particular problem by stopping the graph from being scrolled to an out-of-bounds position (via click and drag).  This is honestly something I should have done from the start, so I apologize that it took this long.  Expect a release shortly with the fix.

> What do you recommend to use then?

I've always recommended [PingPlotter](https://www.pingplotter.com/) for those who want a more feature-rich ping graphing app.  With the caveat that it is not free.

I did a search today and found [PingInfoView](https://www.nirsoft.net/utils/multiple_ping_tool.html) from Nirsoft.  It is free, and like all Nirsoft tools it seems to be quite well done, but it does not have graphing capabilities.

**Comment by bp2008** [comment]
Done in [1.16](https://github.com/bp2008/pingtracer/releases/tag/1.16).
