### ISSUE TITLE
GUI multilanguge

### ISSUE THREAD

**Issue by bovirus** [bp2008/pingtracer#38]
@bp2008 

Could be possible to modify the source code to add option to have a multilanguage GUI?

I can help translating in italian.

**Comment by bp2008** [comment]
Unfortunately I don't have any experience writing apps with multiple language options so I'm not sure what is the best way.  The layout of the app is also very dependent on the rendered size of various text strings, so I think translations would be difficult without having text overlap with other controls.

More importantly, I don't want to put in the time to add the translation capability to this version of PingTracer.  Maybe if I ever make progress on PingTracer 2.x which is a complete redesign.  Trouble is I haven't got the time for that either.
