### ISSUE TITLE
Accidental looping of daily data?

### ISSUE THREAD

**Issue by cpsauer** [bp2008/pingtracer#39]
First and foremost, thanks for making a great piece of software and sharing it with the world! It's been very useful in debugging home network reliability issues.

One thing I noticed and thought I should report: It seems like, if you increase the circular buffer to span multiple days, the data starts looping improperly in the graph. That is, todays data shows up as yesterdays data and data for the day before (in addition to today's data). Any idea why that might be so?

Thanks,
Chris

**Comment by bp2008** [comment]
Hi!

Tools > Options will let you change the "Number of ping responses to cache in memory for each host".  That defines the size of the circular buffer for each graph.

**Comment by cpsauer** [comment]
Hey, @bp2008!

Totally understand that. This is instead about a different issue that appeared after I'd adjusted the buffer to span multiple days via the option you described.

(Where the graph was showing duplicates of todays data for past days when you scrolled back instead of the actual data for those days.)

Thanks again for making something so fantastically useful!

Cheers,
Chris

**Comment by bp2008** [comment]
Oh, I reread and I see you already understood that setting was there.

I'm running a test with minimum buffer size to see what happens.

**Comment by bp2008** [comment]
Yeah so the looping does continue all the way back to the time you started the pings. It should be fairly straightforward for me to adjust that so the graph simply ends instead of looping back around like that.

**Comment by sergeevabc** [comment]
@bp2008, have you managed to solve this issue?

**Comment by bp2008** [comment]
I'm fixing this particular problem by stopping the graph from being scrolled to an out-of-bounds position (via click and drag). This is honestly something I should have done from the start, so I apologize that it took this long.  It is blindingly obvious in hindsignt.

Expect a release shortly with the fix.

**Comment by bp2008** [comment]
Done in [1.16](https://github.com/bp2008/pingtracer/releases/tag/1.16).
