### ISSUE TITLE
Timeline seems broken/unreadable when I switch to "seconds per ping"

### ISSUE THREAD

**Issue by michalpl7** [bp2008/pingtracer#41]
Hello, when I switch to 10 seconds per ping timeline on bottom is broken, this should be easier to read.
It looks like that:
![pingtracer](https://user-images.githubusercontent.com/13987983/191104505-dfad253f-ebbf-4c6d-b103-abd22a1a9266.jpg)

**Comment by bp2008** [comment]
Heh I suppose that would happen.  The code simply tries to label every 1-minute interval and I never re-evaluated that behavior when I made it possible to slow the pings down below 1 per second.

Unfortunately I am not adding new features or significant changes to this app anymore, as it does what I need it to do well enough.

If you want something more feature-rich for long term monitoring, I suggest [Ping Plotter Standard](https://www.pingplotter.com/products/standard).  It is $40 for a perpetual license and it has much more advanced graphing capabilities.
