### ISSUE TITLE
Feature Requests: Remember win size+pos on screen; Make font changeable

### ISSUE THREAD

**Issue by pstein** [bp2008/pingtracer#42]
I would appreciate if PingTracer could remember its windows size and position in screen beyond exit and restart

Moreover the font size should be permanently changeable

Thank you

**Comment by bp2008** [comment]
Hi.  Changing the font size in a Windows Forms app like this is not really possible because the layout is very rigid.  But as of [PingTracer 1.15](https://github.com/bp2008/pingtracer/releases/tag/1.15) the position of the window is now remembered between runs.
