### ISSUE TITLE
Clarification: I think it's windows.  Does it compile in Linux (particularly Ubuntu)

### ISSUE THREAD

**Issue by cpsyctc2** [bp2008/pingtracer#44]
I am a bit reluctant to pull it down and explore as, with my limited software skills, compiling non-Linux things can be a dark if not frankly black hole!  I couldn't see the OS dependency/relatedness anywhere.  Sorry if I'm looking straight through it somewhere.

**Comment by bp2008** [comment]
There is no need to compile it.  Install the `mono-complete` package on ubuntu and then pingtracer.exe downloaded from github's Releases section should be runnable through mono.  I am not sure if everything works well this way because I never test on Linux.  But in theory it should run.

**Comment by cpsyctc2** [comment]
I can confirm that downloading the exe file and installing mono-complete (apt-get install mono-complete) allows me to run the exe on my Ubuntu 22.03 LTS machine.  I haven't had time to explore it much yet but a first test seemed to work fine.  Many thanks both for the reply and the program.
