### ISSUE TITLE
Command Line Args / -h <value> doesn't work

### ISSUE THREAD

**Issue by danielcshn** [bp2008/pingtracer#45]
**Info:**
- Windows 11 23H2 (version 22631.3235)
- Ping Tracer 1.16.0.0

**Code:**
```
.\PingTracer.exe -h 1.1.1.1 -s
```

**Error:**
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
PingTracer.MainForm.ControllerWorker_DoWork(Object sender, DoWorkEventArgs e)
```

**Comment by bp2008** [comment]
Weird.  As that error log doesn't have line numbers, I have no idea where it is breaking.  Can you try running this debug build?

[Debug.zip](https://github.com/bp2008/pingtracer/files/14501920/Debug.zip)

**Comment by bp2008** [comment]
Also I was unable to reproduce the error on my end.  It might help if you could send me your settings file (assuming it has no sensitive info in it).  That is located in `%AppData%\PingTracer`, also accessible via the `Tools` menu, `Open Settings Folder`.

**Comment by danielcshn** [comment]
**settings.cfg**
```
<?xml version="1.0"?>
<Settings xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <logTextOutputToFile>true</logTextOutputToFile>
  <delayMostRecentPing>true</delayMostRecentPing>
  <warnGraphNotLive>true</warnGraphNotLive>
  <hostHistory />
  <cacheSize>10000</cacheSize>
  <fastRefreshScrollingGraphs>true</fastRefreshScrollingGraphs>
  <graphScrollMultiplier>1</graphScrollMultiplier>
  <showDateOnGraphTimeline>true</showDateOnGraphTimeline>
  <lastWindowParams>
    <X>71</X>
    <Y>56</Y>
    <W>624</W>
    <H>620</H>
  </lastWindowParams>
</Settings>
```

**Step by Step:**
- Open the application, host: 8.8.8.8, click to start. Close application.
- Open terminal in application directory. Run the command: .\PingTracer.exe -h 1.1.1.1 -s
- The application opens, the host is not replaced. Auto-start the test at 8.8.8.8 instead of 1.1.1.1. Close application.
- Open the application, delete the host and click to start. Error. Close application.
- Open terminal in application directory. Run the command: .\PingTracer.exe -h 1.1.1.1 -s
- The application opens, the host is blank. Error. Close application.

**Debug:**
```
MainForm.cs:line 340
```

**Comment by bp2008** [comment]
Ok.  The exception is easy enough.  It just happens when you try to start pinging with no hostname defined.  Not a big deal.

The `-h` argument was only intended to be used to select a hostname you'd added previously to the app.  Note the documentation:

```
Arguments:
    -h <value>
        Load a saved configuration with Display Name or Host field matching <value>.
```

I'll add code to make it so if your `-h` value doesn't match anything that already exists, it will be created for you.

Such a janky app this is.  I kind of hate working on it 🤪

**Comment by bp2008** [comment]
[Version 1.17](https://github.com/bp2008/pingtracer/releases) should be more to your liking!
