### ISSUE TITLE
full screen mode overscan

### ISSUE THREAD

**Issue by fragtion** [bp2008/pingtracer#46]
Bug report:

When clicking on the graph so that it becomes exclusive (ie, titlebar etc disappers), **the graph becomes larger than the window was**

So if the window was maximized (=1920x1080) before clicking the graph, now the graph is larger than the display (> 1920x1080), Resulting in details like Last Ping, Min/Max etc to not be visible on the screen, and overflowing onto other monitors

**Comment by bp2008** [comment]
I am aware of that.  What is actually going on is in the normal windowed form, the window actually appears a few pixels smaller than the code said to make it.  But in graph-only view, all that built-in stuff like the title bar and curved corners goes away and the OS actually respects the size the code said to use.

There's definitely a layer of complexity in the window sizing that Ping Tracer's code is simply ignoring.  If I stumble over a box of free time in the future, I will perhaps look into fixing this.

**Comment by fragtion** [comment]
If anyone runs into this same issue and wants a quick fix and is prepared to recompile themselves, this is what worked for me on windows 11:

```
MainForm.cs (line 1107):

- panelForm.SetBounds(this.Left, this.Top, this.Width, this.Height);
+ panelForm.SetBounds(this.Left+7, this.Top, this.Width-14, this.Height-7);
```

**Comment by bp2008** [comment]
These hard-coded offsets are now user-configurable via Tools > Options in [release 1.19.](https://github.com/bp2008/pingtracer/releases/tag/1.19)
