### ISSUE TITLE
Single EXE for download

### ISSUE THREAD

**Issue by pertu** [bp2008/pingtracer#7]
Reason: not everyone has VS installed.
So prebuilt EXE may useful.

You can add releases to repository download list: [https://blog.github.com/2013-07-02-release-your-software/](https://blog.github.com/2013-07-02-release-your-software/)

**Comment by bp2008** [comment]
Is there a problem with the releases that already exist over on the releases tab?

**Comment by xekon** [comment]
I almost asked for the same thing, but i checked over the closed issues first. I generally scan the readme page on github looking for either build instructions or a link to the latest exe download. This is a great tool, I am already finding it very useful, thank you.
