### ISSUE TITLE
24h time format

### ISSUE THREAD

**Issue by bekoit** [bp2008/pingtracer#8]
Great tool. Please add a option to change to 24h time display, like 14:15 instead of 2:15 (pm). At the moment it seems only 12h (AM/PM) is supported. Thanks
![pt](https://user-images.githubusercontent.com/42297038/43992031-8c44b92a-9d78-11e8-8ab9-6ed1f835558a.PNG)
Example shows its 2:38 2:39 2:40 instead 14:38 14:39 14:40 in european time
Date is in correct notation.
Thanks in advance.

**Comment by bp2008** [comment]
Done, try the new version and let me know how it works for you.  There is no option, it should simply honor the PC's region settings.

**Comment by bekoit** [comment]
Works fine, thank you. Great support.
